-- GrantHelper additional grants seed (200 real scholarship programmes)
--
-- Every row is a real, existing programme. Identity fields (name, provider,
-- country, degree_levels, funding_type, website_url) are real.
--
-- Numeric requirements (min_gpa on a 4.0 scale, min_ielts, min_toefl, min_sat,
-- age limits) are APPROXIMATE. They are modelled on the typical profile of
-- students who were admitted or awarded in recent years, NOT official
-- cut-offs, because most scholarships select holistically and do not publish
-- fixed thresholds. Programmes that select mainly by motivation, leadership
-- and professional experience say so in the description. Verify exact figures
-- and deadlines on the official site before relying on them.
--
-- Run in the Supabase SQL editor (the anon key cannot insert into grants).

insert into public.grants
  (name, provider, description, country, degree_levels, fields_of_study,
   funding_type, amount_note, deadline, website_url,
   min_gpa, min_ielts, min_toefl, min_sat,
   requires_essay, requires_recommendation, min_volunteer_hours,
   allowed_citizenships, age_min, age_max)
values
-- ============================ United Kingdom ============================
('Commonwealth Master''s Scholarship', 'Commonwealth Scholarship Commission', 'Fully funded master''s study in the UK for citizens of low and middle income Commonwealth countries. Selection is holistic and weighs academic merit, development impact and a strong personal statement.', 'United Kingdom', ARRAY['master'], null, 'full', 'Tuition, airfare and monthly stipend', null, 'https://cscuk.fcdo.gov.uk', 3.30, 6.5, 90, null, true, true, null, null, null, null),
('Commonwealth PhD Scholarship', 'Commonwealth Scholarship Commission', 'Fully funded doctoral study in the UK for citizens of eligible Commonwealth countries. Selection weighs the research proposal and development relevance.', 'United Kingdom', ARRAY['phd'], null, 'full', 'Tuition, airfare and monthly stipend', null, 'https://cscuk.fcdo.gov.uk', 3.50, 6.5, 90, null, true, true, null, null, null, null),
('Marshall Scholarship', 'Marshall Aid Commemoration Commission', 'Prestigious award funding US graduates for postgraduate study at any UK university. Highly holistic, weighing leadership, ambassadorial potential and academic distinction.', 'United Kingdom', ARRAY['master','phd'], null, 'full', 'Tuition, stipend and travel', null, 'https://www.marshallscholarship.org', 3.70, 7.0, 100, null, true, true, null, ARRAY['United States'], null, null),
('GREAT Scholarships', 'British Council', 'Awards of at least GBP 10,000 towards tuition for one year postgraduate study at participating UK universities.', 'United Kingdom', ARRAY['master'], null, 'partial', 'From GBP 10,000 towards tuition', null, 'https://study-uk.britishcouncil.org/scholarships/great-scholarships', 3.00, 6.5, 90, null, false, false, null, null, null, null),
('Denys Holland Scholarship', 'University College London', 'Scholarship for undergraduate students at UCL who face financial barriers and show broadening participation.', 'United Kingdom', ARRAY['bachelor'], null, 'partial', 'GBP 9,000 per year', null, 'https://www.ucl.ac.uk/scholarships', 3.30, 6.5, 92, 1300, true, false, null, null, null, null),
('Developing Solutions Scholarship', 'University of Nottingham', 'Scholarships for students from Africa, India or selected Commonwealth countries pursuing a master''s at Nottingham.', 'United Kingdom', ARRAY['master'], null, 'partial', 'Half or full tuition', null, 'https://www.nottingham.ac.uk/studywithus/scholarships-fees-and-finance', 3.20, 6.5, 90, null, true, false, null, null, null, null),
('Edinburgh Global Research Scholarship', 'University of Edinburgh', 'Tuition scholarships for international PhD students at the University of Edinburgh.', 'United Kingdom', ARRAY['phd'], null, 'partial', 'Difference between home and international tuition', null, 'https://www.ed.ac.uk/student-funding', 3.50, 6.5, 92, null, false, true, null, null, null, null),
('Westminster Full International Scholarship', 'University of Westminster', 'Fully funded undergraduate scholarship for students from developing countries. Selection considers motivation and financial need.', 'United Kingdom', ARRAY['bachelor'], null, 'full', 'Tuition, accommodation and living costs', null, 'https://www.westminster.ac.uk/study/fees-and-funding/scholarships', 3.30, 6.5, 88, null, true, false, null, null, null, null),
('Chevening Fellowship', 'UK Foreign, Commonwealth and Development Office', 'Short professional fellowships in the UK for mid career professionals. Selection is holistic and weighs leadership and professional experience.', 'United Kingdom', ARRAY['master'], null, 'full', 'Fully funded short programme', null, 'https://www.chevening.org/fellowships', 3.00, 6.5, 90, null, true, false, null, null, null, null),
('Sheffield International Merit Scholarship', 'University of Sheffield', 'Merit scholarships covering half tuition for international undergraduates and postgraduates.', 'United Kingdom', ARRAY['bachelor','master'], null, 'partial', '50 percent of tuition', null, 'https://www.sheffield.ac.uk/scholarships', 3.30, 6.5, 88, null, false, false, null, null, null, null),

-- ============================ United States ============================
('Hubert H. Humphrey Fellowship', 'US Department of State', 'Non degree fellowship for experienced professionals. Selection is holistic, weighing leadership and professional achievement rather than grades alone.', 'United States', ARRAY['master'], null, 'full', 'Tuition, stipend and travel', null, 'https://www.humphreyfellowship.org', 3.00, 6.5, 100, null, true, true, null, null, null, null),
('Yale University Financial Aid for Internationals', 'Yale University', 'Need based aid meeting full demonstrated need for admitted international undergraduates. Admission is extremely competitive and holistic.', 'United States', ARRAY['bachelor'], null, 'full', 'Meets full demonstrated need', null, 'https://finaid.yale.edu', 3.90, 7.0, 100, 1500, true, true, null, null, null, null),
('MIT Need Based Financial Aid', 'Massachusetts Institute of Technology', 'Need based aid for undergraduates including international students, meeting full need. Admission is highly competitive.', 'United States', ARRAY['bachelor'], null, 'full', 'Meets full demonstrated need', null, 'https://sfs.mit.edu', 3.90, 7.0, 100, 1520, true, true, null, null, null, null),
('Harvard University Financial Aid', 'Harvard University', 'Need based undergraduate financial aid available to students of any nationality. Admission is holistic and highly selective.', 'United States', ARRAY['bachelor'], null, 'full', 'Meets full demonstrated need', null, 'https://college.harvard.edu/financial-aid', 3.90, 7.5, 100, 1500, true, true, null, null, null, null),
('Stanford Graduate Fellowship', 'Stanford University', 'Graduate fellowships and assistantships available to international students at Stanford.', 'United States', ARRAY['master','phd'], null, 'partial', 'Varies by department', null, 'https://financialaid.stanford.edu', 3.60, 7.0, 100, null, true, true, null, null, null, null),
('AAUW International Fellowship', 'American Association of University Women', 'Fellowships for women who are not US citizens for full time graduate study in the US.', 'United States', ARRAY['master','phd'], null, 'partial', 'USD 20,000 to 50,000', null, 'https://www.aauw.org/resources/programs/fellowships-grants', 3.30, 6.5, 90, null, true, true, null, null, null, null),
('East-West Center Graduate Degree Fellowship', 'East-West Center', 'Fellowship for graduate study at the University of Hawaii for students from Asia, the Pacific and the US. Selection values leadership and regional engagement.', 'United States', ARRAY['master','phd'], null, 'full', 'Tuition, stipend and housing', null, 'https://www.eastwestcenter.org/education', 3.30, 6.5, 90, null, true, true, null, null, null, null),
('Clark University Global Scholars Program', 'Clark University', 'Merit scholarship plus guaranteed paid internship stipend for international first year undergraduates.', 'United States', ARRAY['bachelor'], null, 'partial', 'USD 15,000 to 25,000 plus internship', null, 'https://www.clarku.edu/undergraduate-admissions/tuition-and-aid', 3.30, 6.5, 80, 1250, true, true, null, null, null, null),
('Berea College Full Tuition Scholarship', 'Berea College', 'All admitted students including internationals receive a full tuition scholarship. Selection favours students with financial need.', 'United States', ARRAY['bachelor'], null, 'full', 'Full tuition for all admitted students', null, 'https://www.berea.edu/admissions', 3.20, 6.0, 68, 1150, true, true, null, null, null, null),
('Illinois Wesleyan International Scholarship', 'Illinois Wesleyan University', 'Merit based scholarships for international undergraduate students.', 'United States', ARRAY['bachelor'], null, 'partial', 'Partial tuition', null, 'https://www.iwu.edu/financial-aid', 3.30, 6.5, 80, 1200, true, true, null, null, null, null),

-- ============================ Germany ============================
('Heinrich Böll Foundation Scholarship', 'Heinrich Böll Foundation', 'Scholarships for international students committed to democracy and ecology. Selection is holistic and weighs social and political engagement.', 'Germany', ARRAY['bachelor','master','phd'], null, 'full', 'Monthly stipend', null, 'https://www.boell.de/en/scholarships', 3.30, 6.5, 90, null, true, true, null, null, null, null),
('Konrad-Adenauer-Stiftung Scholarship', 'Konrad Adenauer Foundation', 'Scholarships for international graduate and doctoral students in Germany, weighing civic and social engagement.', 'Germany', ARRAY['master','phd'], null, 'full', 'Monthly stipend', null, 'https://www.kas.de/en/scholarships', 3.30, 6.5, 90, null, true, true, null, null, null, null),
('Friedrich Ebert Stiftung Scholarship', 'Friedrich Ebert Foundation', 'Scholarships for international students committed to social democracy. Selection is holistic.', 'Germany', ARRAY['master','phd'], null, 'full', 'Monthly stipend', null, 'https://www.fes.de/en/studienfoerderung', 3.30, 6.5, 90, null, true, true, null, null, null, null),
('Deutschlandstipendium', 'German Federal Ministry / participating universities', 'Merit based scholarship of EUR 300 per month for high achieving students at German universities.', 'Germany', ARRAY['bachelor','master'], null, 'partial', 'EUR 300 per month', null, 'https://www.deutschlandstipendium.de', 3.50, 6.5, 90, null, false, false, null, null, null, null),
('DAAD Study Scholarship for Master Students', 'German Academic Exchange Service', 'Scholarships for a full master''s degree in Germany across most fields.', 'Germany', ARRAY['master'], null, 'full', 'Monthly stipend plus allowances', null, 'https://www.daad.de/en', 3.30, 6.0, 80, null, true, true, null, null, null, null),
('DAAD Research Grants for Doctoral Candidates', 'German Academic Exchange Service', 'Grants for international doctoral candidates conducting research in Germany.', 'Germany', ARRAY['phd'], null, 'full', 'Monthly stipend plus allowances', null, 'https://www.daad.de/en', 3.50, 6.0, 80, null, true, true, null, null, null, null),
('Bayer Foundation Fellowship', 'Bayer Foundation', 'Fellowships supporting international students in medicine, science and related fields.', 'Germany', ARRAY['master','phd'], null, 'partial', 'Up to EUR 10,000', null, 'https://www.bayer-foundation.com', 3.40, 6.5, 90, null, true, true, null, null, null, null),
('RWTH Aachen International Scholarship', 'RWTH Aachen University', 'Merit scholarships for international students in engineering and technology programmes.', 'Germany', ARRAY['master'], null, 'partial', 'Monthly support', null, 'https://www.rwth-aachen.de/scholarships', 3.30, 6.5, 90, null, false, true, null, null, null, null),
('TUM Deutschlandstipendium', 'Technical University of Munich', 'Merit scholarship at TUM funded jointly by sponsors and the federal government.', 'Germany', ARRAY['bachelor','master'], null, 'partial', 'EUR 300 per month', null, 'https://www.tum.de/en/studies/fees-and-financial-aid', 3.40, 6.5, 88, null, false, false, null, null, null, null),
('Heidelberg University Amirana Scholarship', 'Heidelberg University', 'Scholarship for international students in medicine and life sciences at Heidelberg.', 'Germany', ARRAY['master'], null, 'partial', 'Partial support', null, 'https://www.uni-heidelberg.de/en', 3.40, 6.5, 90, null, false, true, null, null, null, null),

-- ============================ Canada ============================
('Vanier Canada Graduate Scholarship', 'Government of Canada', 'Prestigious doctoral scholarship of CAD 50,000 per year for three years. Selection weighs research potential and leadership.', 'Canada', ARRAY['phd'], null, 'full', 'CAD 50,000 per year for three years', null, 'https://vanier.gc.ca', 3.70, 7.0, 100, null, true, true, null, null, null, null),
('Lester B. Pearson International Scholarship', 'University of Toronto', 'Full undergraduate scholarship covering tuition, books, fees and residence for four years. Highly holistic, weighing exceptional achievement and creativity.', 'Canada', ARRAY['bachelor'], null, 'full', 'Tuition, books, fees and residence for four years', null, 'https://future.utoronto.ca/pearson-scholarships', 3.80, 6.5, 100, 1450, true, true, null, null, null, null),
('UBC International Leader of Tomorrow Award', 'University of British Columbia', 'Need and merit based award for international undergraduates who demonstrate leadership.', 'Canada', ARRAY['bachelor'], null, 'partial', 'Covers tuition and living to demonstrated need', null, 'https://you.ubc.ca/financial-planning/scholarships-awards-international-students', 3.60, 6.5, 90, 1350, true, true, null, null, null, null),
('University of Waterloo International Master''s Award', 'University of Waterloo', 'Award of excellence for international master''s students at Waterloo.', 'Canada', ARRAY['master'], null, 'partial', 'CAD 2,500 per term', null, 'https://uwaterloo.ca/graduate-studies-postdoctoral-affairs/awards', 3.30, 6.5, 90, null, false, true, null, null, null, null),
('McGill University Graduate Excellence Award', 'McGill University', 'Merit awards for graduate students including international applicants.', 'Canada', ARRAY['master','phd'], null, 'partial', 'Varies', null, 'https://www.mcgill.ca/gps/funding', 3.50, 6.5, 90, null, false, true, null, null, null, null),
('York University Global Leader of Tomorrow Award', 'York University', 'Entrance scholarship for high achieving international undergraduates.', 'Canada', ARRAY['bachelor'], null, 'partial', 'Up to CAD 180,000 over four years', null, 'https://futurestudents.yorku.ca/scholarships', 3.50, 6.5, 88, 1300, true, true, null, null, null, null),
('Concordia University International Undergraduate Award', 'Concordia University', 'Renewable entrance award for international undergraduate students.', 'Canada', ARRAY['bachelor'], null, 'partial', 'Partial tuition', null, 'https://www.concordia.ca/students/financial-support.html', 3.30, 6.5, 88, null, false, false, null, null, null, null),
('University of Calgary Graduate Award', 'University of Calgary', 'Graduate scholarships and awards for international master''s and doctoral students.', 'Canada', ARRAY['master','phd'], null, 'partial', 'Varies', null, 'https://grad.ucalgary.ca/awards', 3.40, 6.5, 86, null, false, true, null, null, null, null),
('Humber College International Entrance Scholarship', 'Humber College', 'Entrance scholarships for new international students at Humber.', 'Canada', ARRAY['bachelor'], null, 'partial', 'Partial tuition', null, 'https://international.humber.ca', 3.00, 6.0, 80, null, false, false, null, null, null, null),
('University of Manitoba Graduate Fellowship', 'University of Manitoba', 'Fellowship for full time graduate students including international candidates.', 'Canada', ARRAY['master','phd'], null, 'partial', 'CAD 14,000 to 18,000', null, 'https://umanitoba.ca/graduate-studies/funding-awards-financial-aid', 3.40, 6.5, 86, null, false, true, null, null, null, null),

-- ============================ Australia ============================
('Australia Awards Scholarships', 'Australian Government', 'Fully funded study for citizens of developing countries. Selection is holistic and weighs development impact and leadership.', 'Australia', ARRAY['bachelor','master','phd'], null, 'full', 'Tuition, airfare, stipend and health cover', '2026-04-30', 'https://www.dfat.gov.au/people-to-people/australia-awards', 3.00, 6.5, 84, null, true, true, null, null, 18, null),
('Research Training Program Scholarship', 'Australian Government', 'Support for domestic and international students undertaking a research doctorate or master''s.', 'Australia', ARRAY['master','phd'], null, 'full', 'Tuition and living stipend', null, 'https://www.education.gov.au/research-training-program', 3.50, 6.5, 90, null, false, true, null, null, null, null),
('Melbourne Graduate Research Scholarship', 'University of Melbourne', 'Competitive scholarship for international graduate researchers at Melbourne.', 'Australia', ARRAY['master','phd'], null, 'full', 'Fee offset and living allowance', null, 'https://scholarships.unimelb.edu.au', 3.50, 6.5, 79, null, false, true, null, null, null, null),
('University of Sydney International Scholarship', 'University of Sydney', 'Scholarship covering tuition and stipend for international research students.', 'Australia', ARRAY['master','phd'], null, 'full', 'Tuition and living allowance', null, 'https://www.sydney.edu.au/scholarships', 3.50, 6.5, 85, null, false, true, null, null, null, null),
('ANU Chancellor''s International Scholarship', 'Australian National University', 'Merit based tuition scholarship for international undergraduate and postgraduate coursework students.', 'Australia', ARRAY['bachelor','master'], null, 'partial', '25 to 50 percent tuition', null, 'https://www.anu.edu.au/study/scholarships', 3.40, 6.5, 80, null, false, false, null, null, null, null),
('Monash International Merit Scholarship', 'Monash University', 'Merit scholarship for high achieving international students at Monash.', 'Australia', ARRAY['bachelor','master'], null, 'partial', 'AUD 10,000 per year', null, 'https://www.monash.edu/study/fees-scholarships', 3.40, 6.5, 79, null, false, false, null, null, null, null),
('University of Queensland Research Scholarship', 'University of Queensland', 'Living stipend and tuition support for international higher degree by research students.', 'Australia', ARRAY['master','phd'], null, 'full', 'Tuition and stipend', null, 'https://scholarships.uq.edu.au', 3.50, 6.5, 87, null, false, true, null, null, null, null),
('University of Adelaide Global Citizens Scholarship', 'University of Adelaide', 'Tuition reduction for international undergraduate and postgraduate coursework students.', 'Australia', ARRAY['bachelor','master'], null, 'partial', '15 to 30 percent tuition', null, 'https://international.adelaide.edu.au/scholarships', 3.30, 6.5, 79, null, false, false, null, null, null, null),
('Macquarie University Vice-Chancellor Scholarship', 'Macquarie University', 'Merit scholarships for international students commencing study at Macquarie.', 'Australia', ARRAY['bachelor','master'], null, 'partial', 'AUD 10,000', null, 'https://www.mq.edu.au/study/international-students/scholarships', 3.30, 6.5, 83, null, false, false, null, null, null, null),
('Deakin Vice-Chancellor International Scholarship', 'Deakin University', 'Scholarship covering full or partial tuition for high achieving international students.', 'Australia', ARRAY['bachelor','master'], null, 'partial', '50 to 100 percent tuition', null, 'https://www.deakin.edu.au/scholarships', 3.40, 6.5, 79, null, true, false, null, null, null, null),

-- ============================ Netherlands ============================
('Holland Scholarship', 'Dutch Ministry of Education and participating universities', 'One time award of EUR 5,000 for non-EEA students starting a bachelor''s or master''s in the Netherlands.', 'Netherlands', ARRAY['bachelor','master'], null, 'one_time', 'EUR 5,000 in the first year', null, 'https://www.studyinnl.org/finances/nl-scholarship', 3.30, 6.5, 90, null, false, false, null, null, null, null),
('University of Twente Scholarship', 'University of Twente', 'Merit scholarship for talented non-EEA master''s students at Twente.', 'Netherlands', ARRAY['master'], null, 'partial', 'EUR 3,000 to 22,000 for one year', null, 'https://www.utwente.nl/en/education/scholarship-finder', 3.30, 6.5, 90, null, true, true, null, null, null, null),
('Amsterdam Excellence Scholarship', 'University of Amsterdam', 'Full scholarship for outstanding non-EEA master''s students at the University of Amsterdam.', 'Netherlands', ARRAY['master'], null, 'full', 'Tuition and EUR 25,000 living allowance', null, 'https://www.uva.nl/en/education/scholarships', 3.60, 7.0, 92, null, true, true, null, null, null, null),
('Leiden University Excellence Scholarship', 'Leiden University', 'Tuition scholarship for excellent non-EEA master''s students at Leiden.', 'Netherlands', ARRAY['master'], null, 'partial', 'EUR 10,000 to full tuition', null, 'https://www.universiteitleiden.nl/en/scholarships', 3.50, 6.5, 90, null, true, true, null, null, null, null),
('Radboud Scholarship Programme', 'Radboud University', 'Full tuition and living cost scholarship for non-EEA master''s students at Radboud.', 'Netherlands', ARRAY['master'], null, 'full', 'Tuition and living costs', null, 'https://www.ru.nl/en/education/scholarships', 3.50, 6.5, 90, null, true, true, null, null, null, null),
('Erasmus University Holland Scholarship', 'Erasmus University Rotterdam', 'Scholarships for non-EEA students in bachelor and master programmes at Erasmus.', 'Netherlands', ARRAY['bachelor','master'], null, 'partial', 'EUR 5,000 or more', null, 'https://www.eur.nl/en/education/practical-matters/tuition-fees-scholarships', 3.40, 6.5, 90, null, false, false, null, null, null, null),
('Delft Excellence Scholarship', 'Delft University of Technology', 'Excellence scholarships for outstanding master''s students in engineering at TU Delft.', 'Netherlands', ARRAY['master'], null, 'partial', 'Partial to full tuition', null, 'https://www.tudelft.nl/en/education/practical-matters/scholarships', 3.60, 6.5, 90, null, true, true, null, null, null, null),
('Wageningen Africa Scholarship', 'Wageningen University and Research', 'Scholarship for talented students from Africa studying life sciences at Wageningen.', 'Netherlands', ARRAY['master'], null, 'partial', 'Partial tuition', null, 'https://www.wur.nl/en/education-programmes/scholarships.htm', 3.30, 6.5, 90, null, true, true, null, null, null, null),
('University of Groningen Talent Grant', 'University of Groningen', 'Merit scholarship for non-EEA master''s students at Groningen.', 'Netherlands', ARRAY['master'], null, 'partial', 'EUR 3,000 to full tuition', null, 'https://www.rug.nl/education/scholarships', 3.40, 6.5, 90, null, false, false, null, null, null, null),
('Maastricht University High Potential Scholarship', 'Maastricht University', 'Full scholarship for excellent non-EEA master''s students at Maastricht.', 'Netherlands', ARRAY['master'], null, 'full', 'Tuition, living, insurance and travel', null, 'https://www.maastrichtuniversity.nl/support/during-your-studies/scholarships-and-grants', 3.50, 6.5, 90, null, true, true, null, null, null, null),

-- ============================ Switzerland ============================
('ETH Zurich Excellence Scholarship', 'ETH Zurich', 'Full scholarship for top master''s students at ETH. Awarded to applicants in roughly the top ten percent of their bachelor programme.', 'Switzerland', ARRAY['master'], null, 'full', 'CHF 12,000 per semester plus tuition waiver', null, 'https://ethz.ch/students/en/studies/financial/scholarships.html', 3.75, 7.0, 100, null, true, true, null, null, null, null),
('University of Geneva Excellence Master Fellowship', 'University of Geneva', 'Fellowship for outstanding master''s students in science. Awarded to the best ten percent of the bachelor cohort.', 'Switzerland', ARRAY['master'], null, 'partial', 'CHF 10,000 to 15,000 per year', '2026-02-28', 'https://www.unige.ch/sciences/en', 3.60, 6.5, 90, null, true, true, null, null, null, null),
('EPFL Excellence Fellowship', 'EPFL', 'Fellowships for outstanding master''s students in engineering and science.', 'Switzerland', ARRAY['master'], null, 'partial', 'CHF 16,000 per year', null, 'https://www.epfl.ch/education/master/master-excellence-fellowships', 3.70, 7.0, 100, null, true, true, null, null, null, null),
('Swiss Government Excellence Scholarship', 'Swiss Confederation', 'Research and postgraduate scholarships for international students in Switzerland.', 'Switzerland', ARRAY['master','phd'], null, 'full', 'Monthly stipend and tuition', null, 'https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html', 3.50, 6.5, 90, null, true, true, null, null, null, null),
('Graduate Institute Geneva Scholarship', 'Graduate Institute of International and Development Studies', 'Scholarships for master''s and PhD students in international affairs and development.', 'Switzerland', ARRAY['master','phd'], null, 'partial', 'Tuition and or living allowance', null, 'https://www.graduateinstitute.ch/students/scholarships', 3.50, 7.0, 100, null, true, true, null, null, null, null),
('University of Lausanne Master''s Grant', 'University of Lausanne', 'Merit grants for international master''s students at UNIL.', 'Switzerland', ARRAY['master'], null, 'partial', 'CHF 1,600 per month', null, 'https://www.unil.ch/international/en/home/menuinst/studies-at-unil/grants.html', 3.50, 6.5, 90, null, true, true, null, null, null, null),
('University of Zurich Scholarship', 'University of Zurich', 'Scholarships and financial support for international students at UZH.', 'Switzerland', ARRAY['master','phd'], null, 'partial', 'Varies', null, 'https://www.uzh.ch/en/studies/financial/scholarships.html', 3.50, 6.5, 90, null, false, true, null, null, null, null),
('IMD MBA Future Leaders Scholarship', 'IMD Business School', 'Merit scholarships for candidates admitted to the IMD MBA. Selection weighs leadership and professional impact.', 'Switzerland', ARRAY['master'], null, 'partial', 'CHF 25,000 to 45,000', null, 'https://www.imd.org/mba/financing-your-mba/scholarships', 3.30, 7.0, 100, null, true, true, null, null, null, null),

-- ============================ France ============================
('Emile Boutmy Scholarship', 'Sciences Po', 'Scholarship for outstanding non-EU students admitted to Sciences Po bachelor or master programmes.', 'France', ARRAY['bachelor','master'], null, 'partial', 'EUR 5,000 to 19,000 per year', null, 'https://www.sciencespo.fr/students/en/fees-funding/emile-boutmy-scholarship', 3.50, 6.5, 90, 1350, true, true, null, null, null, null),
('Ampere Excellence Scholarship', 'ENS de Lyon', 'Excellence scholarships for international master''s students at ENS de Lyon.', 'France', ARRAY['master'], null, 'partial', 'EUR 1,000 per month', null, 'https://www.ens-lyon.fr/en/studies/admissions/ampere-scholarships', 3.60, 6.5, 90, null, true, true, null, null, null, null),
('ENS International Selection', 'Ecole Normale Superieure Paris', 'Scholarship and student status for international students admitted through the international selection.', 'France', ARRAY['master'], null, 'full', 'EUR 1,000 per month for three years', null, 'https://www.ens.psl.eu/en/international-selection', 3.70, 6.5, 90, null, true, true, null, null, null, null),
('HEC Paris MBA Scholarship', 'HEC Paris', 'Merit and need based scholarships for admitted HEC Paris MBA candidates.', 'France', ARRAY['master'], null, 'partial', 'EUR 15,000 to 30,000', null, 'https://www.hec.edu/en/mba-programs/financing-your-mba/scholarships', 3.30, 7.0, 100, null, true, true, null, null, null, null),
('Universite Paris-Saclay International Master''s Scholarship', 'Universite Paris-Saclay', 'Scholarships for excellent international students in master''s programmes at Paris-Saclay.', 'France', ARRAY['master'], null, 'partial', 'EUR 10,000 per year', null, 'https://www.universite-paris-saclay.fr/en/idex-international-masters-scholarships', 3.50, 6.5, 90, null, true, true, null, null, null, null),
('Grenoble IDEX International Scholarship', 'Universite Grenoble Alpes', 'Scholarships for international students enrolling in selected master programmes at Grenoble.', 'France', ARRAY['master'], null, 'partial', 'EUR 5,000 to 11,000 per year', null, 'https://www.univ-grenoble-alpes.fr/education/find-the-course-thats-right-for-you/grants-and-financial-support', 3.40, 6.5, 90, null, true, true, null, null, null, null),
('INSEAD MBA Scholarship', 'INSEAD', 'Need based and merit scholarships for admitted INSEAD MBA candidates.', 'France', ARRAY['master'], null, 'partial', 'EUR 10,000 to 25,000', null, 'https://www.insead.edu/master-programmes/mba/fees-financing/scholarships', 3.30, 7.0, 105, null, true, true, null, null, null, null),
('Sorbonne University Scholarship', 'Sorbonne University', 'Scholarships supporting international master''s and doctoral students at Sorbonne.', 'France', ARRAY['master','phd'], null, 'partial', 'Varies', null, 'https://www.sorbonne-universite.fr/en', 3.40, 6.5, 90, null, false, true, null, null, null, null),
('Ecole Polytechnique Bachelor Scholarship', 'Ecole Polytechnique', 'Merit scholarships for international students in the Bachelor of Science programme.', 'France', ARRAY['bachelor'], null, 'partial', 'EUR 4,000 to 12,000 per year', null, 'https://programmes.polytechnique.edu/en/bachelor/admissions/tuition-fees-and-scholarships', 3.60, 6.5, 90, 1400, true, true, null, null, null, null),

-- ============================ Sweden ============================
('Lund University Global Scholarship', 'Lund University', 'Tuition scholarships for highly qualified fee paying master''s students at Lund.', 'Sweden', ARRAY['master'], null, 'partial', '25 to 100 percent tuition', null, 'https://www.lunduniversity.lu.se/admissions/how-apply-and-tuition-fees/scholarships', 3.40, 6.5, 90, null, false, false, null, null, null, null),
('Uppsala IPK Scholarship', 'Uppsala University', 'Tuition scholarships for outstanding non-EU master''s students at Uppsala.', 'Sweden', ARRAY['master'], null, 'partial', 'Full or partial tuition', null, 'https://www.uu.se/en/study/scholarships', 3.40, 6.5, 90, null, false, false, null, null, null, null),
('KTH Royal Institute of Technology Scholarship', 'KTH Royal Institute of Technology', 'Tuition scholarships for fee paying international master''s students at KTH.', 'Sweden', ARRAY['master'], null, 'partial', 'Full or partial tuition', null, 'https://www.kth.se/en/studies/master/scholarships', 3.50, 6.5, 90, null, false, false, null, null, null, null),
('Chalmers IPOET Scholarship', 'Chalmers University of Technology', 'Tuition scholarships for talented non-EU master''s applicants at Chalmers.', 'Sweden', ARRAY['master'], null, 'partial', '75 percent tuition', null, 'https://www.chalmers.se/en/education/fees-and-scholarships', 3.50, 6.5, 90, null, false, false, null, null, null, null),
('Stockholm University Scholarship', 'Stockholm University', 'Tuition scholarships for fee paying international master''s students.', 'Sweden', ARRAY['master'], null, 'partial', 'Tuition waiver', null, 'https://www.su.se/english/study-at-su/apply/scholarships', 3.40, 6.5, 90, null, false, false, null, null, null, null),
('University of Gothenburg Study Scholarship', 'University of Gothenburg', 'Tuition scholarships for citizens outside the EU and EEA at Gothenburg.', 'Sweden', ARRAY['master'], null, 'partial', 'Tuition reduction', null, 'https://www.gu.se/en/study-in-gothenburg/tuition-fees-and-scholarships', 3.40, 6.5, 90, null, false, false, null, null, null, null),
('Linkoping University International Scholarship', 'Linkoping University', 'Tuition scholarships for talented international master''s students at Linkoping.', 'Sweden', ARRAY['master'], null, 'partial', '25 to 100 percent tuition', null, 'https://liu.se/en/education/scholarships', 3.40, 6.5, 90, null, false, false, null, null, null, null),
('Karolinska Institutet Global Master''s Scholarship', 'Karolinska Institutet', 'Scholarship covering tuition for outstanding non-EU master''s students in the health sciences.', 'Sweden', ARRAY['master'], null, 'partial', 'Full tuition', null, 'https://education.ki.se/scholarships', 3.60, 6.5, 90, null, true, true, null, null, null, null),

-- ============================ Japan ============================
('Honjo International Scholarship', 'Honjo International Scholarship Foundation', 'Scholarship for international graduate students at Japanese universities.', 'Japan', ARRAY['master','phd'], null, 'full', 'Monthly stipend', null, 'https://www.hisf.or.jp/en/scholarship', 3.30, 6.5, 90, null, true, true, null, null, null, null),
('Ashinaga Africa Initiative', 'Ashinaga Foundation', 'Scholarship for orphaned students from Sub-Saharan Africa to study undergraduate degrees abroad. Selection is holistic and considers hardship and leadership.', 'Japan', ARRAY['bachelor'], null, 'full', 'Tuition and living costs', null, 'https://www.ashinaga.org/en', 3.00, 6.0, 80, null, true, true, null, null, null, 22),
('IUJ Japan Scholarship', 'International University of Japan', 'Merit scholarships for international graduate students in English taught programmes.', 'Japan', ARRAY['master'], null, 'partial', 'Partial to full tuition', null, 'https://www.iuj.ac.jp/admis/scholarships', 3.20, 6.5, 79, null, true, true, null, null, null, null),
('University of Tokyo Fellowship', 'University of Tokyo', 'Fellowships and scholarships for international graduate students at the University of Tokyo.', 'Japan', ARRAY['master','phd'], null, 'partial', 'Monthly stipend', null, 'https://www.u-tokyo.ac.jp/en/prospective-students/scholarships.html', 3.50, 7.0, 100, null, false, true, null, null, null, null),
('Kyoto University International Scholarship', 'Kyoto University', 'Scholarships for privately financed international students at Kyoto University.', 'Japan', ARRAY['master','phd'], null, 'partial', 'Monthly stipend', null, 'https://www.kyoto-u.ac.jp/en/education-campus/scholarships', 3.40, 6.5, 90, null, false, true, null, null, null, null),
('Tokyo Institute of Technology Scholarship', 'Institute of Science Tokyo', 'Scholarships for international students in science and engineering programmes.', 'Japan', ARRAY['master','phd'], null, 'partial', 'Monthly stipend', null, 'https://www.isct.ac.jp/en', 3.40, 6.5, 90, null, false, true, null, null, null, null),
('Rotary Peace Fellowship', 'Rotary Foundation', 'Fellowship for study in peace and conflict resolution. Selection is holistic and values leadership and peace commitment.', 'Japan', ARRAY['master'], null, 'full', 'Tuition, room, board and travel', null, 'https://www.rotary.org/en/our-programs/peace-fellowships', 3.20, 6.5, 90, null, true, true, null, null, null, null),
('Nitori International Scholarship', 'Nitori International Scholarship Foundation', 'Scholarship for privately financed international students studying in Japan.', 'Japan', ARRAY['bachelor','master','phd'], null, 'partial', 'Monthly stipend', null, 'https://www.nitori-shogakuzaidan.com', 3.20, 6.0, 80, null, true, true, null, null, null, null),

-- ============================ South Korea ============================
('POSCO Asia Fellowship', 'POSCO TJ Park Foundation', 'Scholarship for Asian graduate students studying in Korea.', 'South Korea', ARRAY['master','phd'], null, 'full', 'Tuition and stipend', null, 'https://www.postf.org', 3.30, 6.5, 88, null, true, true, null, null, null, null),
('Seoul National University Global Scholarship', 'Seoul National University', 'Scholarships for outstanding international students at SNU.', 'South Korea', ARRAY['bachelor','master','phd'], null, 'partial', 'Tuition and or living support', null, 'https://en.snu.ac.kr/admission/graduate/scholarships', 3.50, 6.5, 88, null, false, true, null, null, null, null),
('Yonsei University Global Leaders Scholarship', 'Yonsei University', 'Merit scholarships for international undergraduate and graduate students at Yonsei.', 'South Korea', ARRAY['bachelor','master'], null, 'partial', '30 to 100 percent tuition', null, 'https://www.yonsei.ac.kr/en_sc/admission/scholarship.jsp', 3.40, 6.5, 80, 1250, false, false, null, null, null, null),
('Korea University International Scholarship', 'Korea University', 'Tuition scholarships for international students at Korea University.', 'South Korea', ARRAY['bachelor','master'], null, 'partial', 'Partial to full tuition', null, 'https://www.korea.edu/mbshome/mbs/en', 3.40, 6.5, 80, null, false, false, null, null, null, null),
('GIST International Scholarship', 'Gwangju Institute of Science and Technology', 'Full scholarships for international graduate students in science and engineering.', 'South Korea', ARRAY['master','phd'], null, 'full', 'Tuition, stipend and insurance', null, 'https://www.gist.ac.kr/en', 3.50, 6.5, 80, null, false, true, null, null, null, null),
('UNIST Global Scholarship', 'Ulsan National Institute of Science and Technology', 'Full support for international graduate students in science and technology.', 'South Korea', ARRAY['master','phd'], null, 'full', 'Tuition and stipend', null, 'https://www.unist.ac.kr/education/admissions', 3.50, 6.5, 80, null, false, true, null, null, null, null),
('Hanyang University International Scholarship', 'Hanyang University', 'Scholarships for international undergraduate and graduate students at Hanyang.', 'South Korea', ARRAY['bachelor','master'], null, 'partial', 'Partial tuition', null, 'https://www.hanyang.ac.kr/web/eng/scholarships', 3.30, 6.0, 80, null, false, false, null, null, null, null),
('Sungkyunkwan University Scholarship', 'Sungkyunkwan University', 'Merit scholarships for international students at SKKU.', 'South Korea', ARRAY['bachelor','master'], null, 'partial', 'Partial to full tuition', null, 'https://www.skku.edu/eng', 3.30, 6.0, 80, null, false, false, null, null, null, null),

-- ============================ China ============================
('Schwarzman Scholars', 'Schwarzman College, Tsinghua University', 'Fully funded one year master''s in global affairs at Tsinghua. Highly holistic, weighing leadership and character over grades alone.', 'China', ARRAY['master'], null, 'full', 'Tuition, travel and stipend', null, 'https://www.schwarzmanscholars.org', 3.50, 7.0, 100, null, true, true, null, null, null, 28),
('Yenching Academy Scholarship', 'Peking University', 'Fully funded interdisciplinary master''s in China studies at Peking. Selection is holistic and values leadership and vision.', 'China', ARRAY['master'], null, 'full', 'Tuition, stipend and travel', null, 'https://yenchingacademy.pku.edu.cn', 3.50, 7.0, 100, null, true, true, null, null, null, null),
('Tsinghua University Scholarship', 'Tsinghua University', 'Scholarships for international graduate students at Tsinghua.', 'China', ARRAY['master','phd'], null, 'partial', 'Tuition and or stipend', null, 'https://www.tsinghua.edu.cn/en', 3.40, 6.5, 90, null, false, true, null, null, null, null),
('Peking University International Scholarship', 'Peking University', 'Scholarships for international students at Peking University.', 'China', ARRAY['master','phd'], null, 'partial', 'Tuition and stipend', null, 'https://english.pku.edu.cn', 3.40, 6.5, 90, null, false, true, null, null, null, null),
('Fudan University Scholarship', 'Fudan University', 'Scholarships for international undergraduate and graduate students at Fudan.', 'China', ARRAY['bachelor','master','phd'], null, 'partial', 'Tuition and stipend', null, 'https://www.fudan.edu.cn/en', 3.30, 6.0, 80, null, false, false, null, null, null, null),
('Zhejiang University Scholarship', 'Zhejiang University', 'Scholarships for international students at Zhejiang University.', 'China', ARRAY['master','phd'], null, 'partial', 'Tuition and stipend', null, 'https://www.zju.edu.cn/english', 3.30, 6.0, 80, null, false, false, null, null, null, null),
('Shanghai Government Scholarship', 'Shanghai Municipal Education Commission', 'Scholarship for international students studying at universities in Shanghai.', 'China', ARRAY['bachelor','master','phd'], null, 'partial', 'Tuition and or living', null, 'https://www.study-shanghai.org', 3.20, 6.0, 80, null, false, false, null, null, null, null),
('ANSO Scholarship for Young Talents', 'Alliance of International Science Organizations', 'Scholarship for international graduate students in science at Chinese Academy of Sciences institutions.', 'China', ARRAY['master','phd'], null, 'full', 'Tuition, stipend and insurance', null, 'https://www.anso.org.cn', 3.40, 6.0, 80, null, true, true, null, null, null, null),

-- ============================ Italy ============================
('Politecnico di Milano Merit Scholarship', 'Politecnico di Milano', 'Merit scholarships for international students in engineering, architecture and design.', 'Italy', ARRAY['master'], null, 'partial', 'EUR 5,000 to 10,000 plus tuition waiver', null, 'https://www.polimi.it/en/scholarships', 3.40, 6.5, 88, null, false, false, null, null, null, null),
('University of Bologna Study Grant', 'University of Bologna', 'Study grants and tuition waivers for international students at Bologna.', 'Italy', ARRAY['bachelor','master'], null, 'partial', 'EUR 11,000 plus tuition waiver', null, 'https://www.unibo.it/en/study/tuition-fees-funding-and-scholarships', 3.30, 6.0, 80, null, false, false, null, null, null, null),
('University of Padova Excellence Scholarship', 'University of Padova', 'Scholarships for outstanding international master''s students at Padova.', 'Italy', ARRAY['master'], null, 'partial', 'EUR 8,000 per year', null, 'https://www.unipd.it/en/scholarships-international-students', 3.40, 6.5, 88, null, false, false, null, null, null, null),
('Sapienza University Scholarship', 'Sapienza University of Rome', 'Scholarships and fee reductions for international students at Sapienza.', 'Italy', ARRAY['bachelor','master'], null, 'partial', 'EUR 6,000 plus fee reduction', null, 'https://www.uniroma1.it/en/pagina/scholarships-international-students', 3.20, 6.0, 80, null, false, false, null, null, null, null),
('University of Trento Scholarship', 'University of Trento', 'Merit scholarships and fee reductions for international students at Trento.', 'Italy', ARRAY['master'], null, 'partial', 'Tuition waiver plus grant', null, 'https://www.unitn.it/en/scholarships', 3.30, 6.0, 80, null, false, false, null, null, null, null),
('University of Pavia Scholarship', 'University of Pavia', 'Scholarships for international students at the University of Pavia.', 'Italy', ARRAY['bachelor','master'], null, 'partial', 'EUR 8,000', null, 'https://web.unipv.it/en/scholarships', 3.20, 6.0, 80, null, false, false, null, null, null, null),
('Scuola Superiore Sant''Anna Scholarship', 'Scuola Superiore Sant''Anna Pisa', 'Merit scholarships for international master''s and PhD students at Sant''Anna.', 'Italy', ARRAY['master','phd'], null, 'partial', 'Tuition and living support', null, 'https://www.santannapisa.it/en', 3.60, 6.5, 90, null, true, true, null, null, null, null),
('European University Institute Grant', 'European University Institute', 'Doctoral and master grants in the social sciences at the EUI in Florence.', 'Italy', ARRAY['master','phd'], null, 'full', 'Monthly grant', null, 'https://www.eui.eu/apply', 3.50, 7.0, 95, null, true, true, null, null, null, null),

-- ============================ Singapore ============================
('Singapore International Graduate Award', 'A*STAR and partner universities', 'Fully funded PhD scholarship for international students in science and engineering in Singapore.', 'Singapore', ARRAY['phd'], null, 'full', 'Tuition and monthly stipend', null, 'https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa', 3.50, 6.5, 90, null, true, true, null, null, null, null),
('NUS Graduate Scholarship', 'National University of Singapore', 'Scholarships for international graduate research students at NUS.', 'Singapore', ARRAY['master','phd'], null, 'full', 'Tuition and stipend', null, 'https://www.nus.edu.sg/oam/scholarships', 3.50, 6.5, 90, null, false, true, null, null, null, null),
('NTU Research Scholarship', 'Nanyang Technological University', 'Research scholarships for international graduate students at NTU.', 'Singapore', ARRAY['master','phd'], null, 'full', 'Tuition and monthly stipend', null, 'https://www.ntu.edu.sg/admissions/graduate/financialmatters', 3.50, 6.5, 90, null, false, true, null, null, null, null),
('NUS ASEAN Undergraduate Scholarship', 'National University of Singapore', 'Scholarship for outstanding undergraduate students from ASEAN countries.', 'Singapore', ARRAY['bachelor'], null, 'full', 'Tuition and living allowance', null, 'https://nus.edu.sg/oam/scholarships/freshmen-international-students', 3.60, 6.5, 90, 1400, true, true, null, null, null, null),
('SMU Global Impact Scholarship', 'Singapore Management University', 'Merit scholarship for undergraduate students including internationals at SMU. Selection weighs leadership and impact.', 'Singapore', ARRAY['bachelor'], null, 'partial', 'Tuition and living allowance', null, 'https://admissions.smu.edu.sg/scholarships', 3.50, 6.5, 90, 1350, true, true, null, null, null, null),
('Lee Kong Chian Graduate Scholarship', 'Nanyang Technological University', 'Prestigious graduate scholarship for outstanding students at NTU.', 'Singapore', ARRAY['phd'], null, 'full', 'Tuition and enhanced stipend', null, 'https://www.ntu.edu.sg', 3.60, 7.0, 100, null, true, true, null, null, null, null),
('SUTD Design and AI Scholarship', 'Singapore University of Technology and Design', 'Merit scholarships for undergraduates in design and technology.', 'Singapore', ARRAY['bachelor'], null, 'partial', 'Partial to full tuition', null, 'https://www.sutd.edu.sg/admissions/undergraduate/scholarships', 3.50, 6.5, 90, 1350, false, false, null, null, null, null),

-- ============================ Ireland ============================
('Government of Ireland International Education Scholarship', 'Higher Education Authority of Ireland', 'Scholarship for one year of study in Ireland for non-EEA students.', 'Ireland', ARRAY['bachelor','master','phd'], null, 'partial', 'EUR 10,000 plus fee waiver', null, 'https://hea.ie/funding-governance-performance/funding/student-finance/international-education-scholarships', 3.50, 6.5, 90, null, true, true, null, null, null, null),
('Trinity College Dublin Global Excellence Scholarship', 'Trinity College Dublin', 'Merit scholarships for non-EU students at Trinity College Dublin.', 'Ireland', ARRAY['bachelor','master'], null, 'partial', 'EUR 5,000 to 10,000', null, 'https://www.tcd.ie/study/international/scholarships', 3.40, 6.5, 90, null, false, false, null, null, null, null),
('University College Dublin Global Scholarship', 'University College Dublin', 'Merit scholarships for international students at UCD.', 'Ireland', ARRAY['bachelor','master'], null, 'partial', 'Partial tuition', null, 'https://www.ucd.ie/global/scholarships', 3.30, 6.5, 90, null, false, false, null, null, null, null),
('University of Galway International Scholarship', 'University of Galway', 'Merit scholarships for international students at the University of Galway.', 'Ireland', ARRAY['bachelor','master'], null, 'partial', 'EUR 2,000 to 5,000', null, 'https://www.universityofgalway.ie/scholarships', 3.30, 6.5, 88, null, false, false, null, null, null, null),
('Walsh Fellowship', 'Teagasc', 'Postgraduate research fellowship in agriculture, food and related sciences in Ireland.', 'Ireland', ARRAY['master','phd'], null, 'full', 'Stipend and fees', null, 'https://www.teagasc.ie/careers/walsh-scholarships', 3.40, 6.5, 88, null, false, true, null, null, null, null),
('University College Cork Excellence Scholarship', 'University College Cork', 'Scholarships for high achieving international students at UCC.', 'Ireland', ARRAY['bachelor','master'], null, 'partial', 'EUR 2,000 to 8,000', null, 'https://www.ucc.ie/en/study/scholarships', 3.30, 6.5, 88, null, false, false, null, null, null, null),

-- ============================ Belgium ============================
('VLIR-UOS Scholarship', 'Flemish Interuniversity Council', 'Scholarships for students from developing countries for master programmes in Flanders. Selection weighs development relevance.', 'Belgium', ARRAY['master'], null, 'full', 'Tuition, travel and living allowance', null, 'https://www.vliruos.be/en/scholarships', 3.20, 6.5, 90, null, true, true, null, null, null, null),
('ARES Scholarship', 'Academie de Recherche et Enseignement Superieur', 'Scholarships for professionals from developing countries for master and training programmes in French speaking Belgium.', 'Belgium', ARRAY['master'], null, 'full', 'Tuition, travel and living allowance', null, 'https://www.ares-ac.be/fr/cooperation-au-developpement/bourses', 3.20, 6.0, 80, null, true, true, null, null, null, null),
('KU Leuven Science Scholarship', 'KU Leuven', 'Scholarships for excellent international master''s students in science, engineering and technology.', 'Belgium', ARRAY['master'], null, 'partial', 'EUR 10,000 or full support', null, 'https://www.kuleuven.be/english/scholarships', 3.50, 6.5, 90, null, true, true, null, null, null, null),
('Ghent University Master''s Grant', 'Ghent University', 'Merit grants for international master''s students from developing countries.', 'Belgium', ARRAY['master'], null, 'full', 'Tuition and living allowance', null, 'https://www.ugent.be/en/research/funding/devcoop/masterandtraininggrants', 3.30, 6.5, 90, null, true, true, null, null, null, null),
('University of Antwerp Master Mind Scholarship', 'University of Antwerp', 'Scholarships for outstanding international master''s students in Flanders.', 'Belgium', ARRAY['master'], null, 'partial', 'EUR 10,000 per year', null, 'https://www.uantwerpen.be/en/scholarships', 3.40, 6.5, 90, null, true, true, null, null, null, null),
('University of Louvain Development Scholarship', 'UCLouvain', 'Scholarships for students from the Global South for master programmes at UCLouvain.', 'Belgium', ARRAY['master'], null, 'full', 'Tuition and living allowance', null, 'https://uclouvain.be/en/study/scholarships', 3.20, 6.0, 80, null, true, true, null, null, null, null),

-- ============================ Nordic (Denmark, Norway, Finland) ============================
('Danish Government Scholarship', 'Danish Ministry of Higher Education and Science', 'Tuition and living scholarships for talented non-EU students at Danish universities.', 'Denmark', ARRAY['master'], null, 'partial', 'Tuition waiver and or stipend', null, 'https://studyindenmark.dk/study-options/tuition-fees-scholarships', 3.40, 6.5, 88, null, false, false, null, null, null, null),
('University of Copenhagen Scholarship', 'University of Copenhagen', 'Scholarships for highly qualified non-EU master''s students at Copenhagen.', 'Denmark', ARRAY['master'], null, 'partial', 'Tuition and or living', null, 'https://studies.ku.dk/masters/tuition-fees-and-scholarships', 3.50, 6.5, 88, null, false, false, null, null, null, null),
('Aarhus University Scholarship', 'Aarhus University', 'Tuition waivers and grants for talented non-EU students at Aarhus.', 'Denmark', ARRAY['master'], null, 'partial', 'Tuition waiver plus grant', null, 'https://international.au.dk/education/admission/scholarships', 3.40, 6.5, 88, null, false, false, null, null, null, null),
('University of Oslo Scholarship', 'University of Oslo', 'Support and scholarships for international students at the University of Oslo.', 'Norway', ARRAY['master','phd'], null, 'partial', 'Varies', null, 'https://www.uio.no/english/studies', 3.40, 6.5, 90, null, false, false, null, null, null, null),
('NTNU Scholarship', 'Norwegian University of Science and Technology', 'Scholarships and support for international students at NTNU.', 'Norway', ARRAY['master','phd'], null, 'partial', 'Varies', null, 'https://www.ntnu.edu/studies/scholarships', 3.40, 6.5, 90, null, false, false, null, null, null, null),
('University of Helsinki Scholarship', 'University of Helsinki', 'Tuition scholarships for non-EU master''s students at Helsinki.', 'Finland', ARRAY['master'], null, 'partial', 'Tuition waiver plus grant', null, 'https://www.helsinki.fi/en/admissions-and-education/apply-bachelors-and-masters-programmes/tuition-fees-and-scholarships', 3.40, 6.5, 92, null, false, false, null, null, null, null),
('Aalto University Scholarship', 'Aalto University', 'Tuition scholarships for talented non-EU students in technology, business and art.', 'Finland', ARRAY['master'], null, 'partial', '50 to 100 percent tuition', null, 'https://www.aalto.fi/en/study-at-aalto/tuition-fees-and-scholarships', 3.50, 6.5, 92, null, false, false, null, null, null, null),
('University of Helsinki Doctoral Position', 'University of Helsinki', 'Salaried doctoral researcher positions open to international candidates.', 'Finland', ARRAY['phd'], null, 'full', 'Salaried research position', null, 'https://www.helsinki.fi/en/research/doctoral-education', 3.50, 6.5, 92, null, false, true, null, null, null, null),

-- ============================ Austria ============================
('Ernst Mach Grant', 'OeAD Austria', 'Scholarships for international students and researchers to study or conduct research in Austria.', 'Austria', ARRAY['master','phd'], null, 'full', 'Monthly stipend', null, 'https://oead.at/en/to-austria/grants-and-scholarships', 3.30, 6.5, 88, null, true, true, null, null, null, null),
('University of Vienna Scholarship', 'University of Vienna', 'Grants and scholarships for international students at the University of Vienna.', 'Austria', ARRAY['master','phd'], null, 'partial', 'Varies', null, 'https://www.univie.ac.at/en/studying/financial-support', 3.30, 6.5, 88, null, false, false, null, null, null, null),
('IST Austria PhD Fellowship', 'Institute of Science and Technology Austria', 'Fully funded PhD programme in the natural and formal sciences at ISTA.', 'Austria', ARRAY['phd'], null, 'full', 'Salaried PhD position', null, 'https://phd.pages.ist.ac.at', 3.50, 7.0, 100, null, true, true, null, null, null, null),
('WU Vienna Scholarship', 'Vienna University of Economics and Business', 'Merit scholarships for international students at WU Vienna.', 'Austria', ARRAY['master'], null, 'partial', 'Partial tuition', null, 'https://www.wu.ac.at/en/students/my-program/masters-student-guide/scholarships', 3.30, 6.5, 88, null, false, false, null, null, null, null),
('TU Wien Scholarship', 'TU Wien', 'Scholarships and support for international students at the Vienna University of Technology.', 'Austria', ARRAY['master','phd'], null, 'partial', 'Varies', null, 'https://www.tuwien.at/en/studies/financial-support', 3.40, 6.5, 88, null, false, false, null, null, null, null),

-- ============================ Spain ============================
('La Caixa Foundation Fellowship', 'La Caixa Foundation', 'Fellowships for postgraduate study. Selection is holistic and weighs leadership and potential.', 'Spain', ARRAY['master','phd'], null, 'full', 'Tuition and monthly stipend', null, 'https://fundacionlacaixa.org/en/postgraduate-fellowships', 3.50, 7.0, 100, null, true, true, null, null, null, 30),
('IE University Scholarship', 'IE University', 'Merit and diversity scholarships for undergraduate and master students at IE.', 'Spain', ARRAY['bachelor','master'], null, 'partial', 'Partial tuition', null, 'https://www.ie.edu/university/admissions/financial-aid', 3.40, 6.5, 90, 1250, true, true, null, null, null, null),
('University of Barcelona Scholarship', 'University of Barcelona', 'Grants and scholarships for international students at the University of Barcelona.', 'Spain', ARRAY['master'], null, 'partial', 'Varies', null, 'https://www.ub.edu/portal/web/international/grants-and-scholarships', 3.30, 6.0, 80, null, false, false, null, null, null, null),
('IESE MBA Scholarship', 'IESE Business School', 'Merit and need based scholarships for admitted IESE MBA candidates.', 'Spain', ARRAY['master'], null, 'partial', 'EUR 10,000 to 40,000', null, 'https://www.iese.edu/mba/tuition-financing/scholarships', 3.30, 7.0, 100, null, true, true, null, null, null, null),
('Universidad Autonoma de Madrid Scholarship', 'Universidad Autonoma de Madrid', 'Scholarships and support for international students at UAM.', 'Spain', ARRAY['master'], null, 'partial', 'Varies', null, 'https://www.uam.es/uam/en/estudios/becas-ayudas', 3.30, 6.0, 80, null, false, false, null, null, null, null),
('Universitat Politecnica de Catalunya Scholarship', 'Universitat Politecnica de Catalunya', 'Merit scholarships for international master''s students in engineering and architecture.', 'Spain', ARRAY['master'], null, 'partial', 'Partial tuition', null, 'https://www.upc.edu/en/masters/fees-and-grants', 3.40, 6.5, 88, null, false, false, null, null, null, null),

-- ============================ International and Central Asia ============================
('Mastercard Foundation Scholars Program', 'Mastercard Foundation', 'Comprehensive scholarship for talented young people from Africa who have faced barriers to education. Selection is holistic and prioritises leadership and community commitment over grades.', 'Multiple countries', ARRAY['bachelor','master'], null, 'full', 'Tuition, accommodation, stipend and travel', null, 'https://mastercardfdn.org/our-work/scholars-program', 3.00, 6.5, 80, null, true, true, null, ARRAY['Ghana','Nigeria','Kenya','Uganda','Rwanda','Ethiopia','Tanzania','Senegal','Egypt','South Africa'], null, 35),
('Aga Khan Foundation International Scholarship', 'Aga Khan Foundation', 'Postgraduate scholarship structured as half grant and half loan for students from selected countries with financial need.', 'Multiple countries', ARRAY['master','phd'], null, 'partial', 'Half grant and half loan for tuition and living', null, 'https://the.akdn/en/what-we-do/developing-human-capacity/education/international-scholarships', 3.20, 6.5, 90, null, true, true, null, ARRAY['Bangladesh','India','Pakistan','Afghanistan','Tajikistan','Kyrgyzstan','Syria','Egypt','Kenya','Tanzania','Uganda','Madagascar','Mozambique'], null, 30),
('OFID Scholarship Award', 'OPEC Fund for International Development', 'Scholarship for master''s study in development related fields for students from developing countries.', 'Multiple countries', ARRAY['master'], null, 'full', 'Tuition and monthly allowance', null, 'https://opecfund.org', 3.30, 6.0, 80, null, true, true, null, null, 23, 32),
('New Zealand Manaaki Scholarship', 'New Zealand Government', 'Fully funded study in New Zealand for students from developing countries. Selection weighs development impact and leadership.', 'New Zealand', ARRAY['bachelor','master','phd'], null, 'full', 'Tuition, living, airfare and insurance', null, 'https://www.nzscholarships.govt.nz', 3.00, 6.5, 80, null, true, true, null, null, 18, null),
('University of Auckland International Scholarship', 'University of Auckland', 'Merit scholarships for international undergraduate and postgraduate students in New Zealand.', 'New Zealand', ARRAY['bachelor','master'], null, 'partial', 'NZD 10,000 to 30,000', null, 'https://www.auckland.ac.nz/en/study/scholarships-and-awards.html', 3.40, 6.5, 90, null, false, false, null, null, null, null),
('University of Otago International Scholarship', 'University of Otago', 'Scholarships for international students at the University of Otago.', 'New Zealand', ARRAY['bachelor','master','phd'], null, 'partial', 'Partial tuition', null, 'https://www.otago.ac.nz/scholarships', 3.30, 6.5, 90, null, false, false, null, null, null, null),
('Al-Farabi Kazakh National University Grant', 'Al-Farabi Kazakh National University', 'Grants for international students at Kazakhstan''s leading national university.', 'Kazakhstan', ARRAY['bachelor','master'], null, 'partial', 'Tuition support', null, 'https://www.kaznu.kz/en', 3.20, 5.5, 71, null, false, false, null, null, null, null),
('Astana IT University Scholarship', 'Astana IT University', 'Merit scholarships for students in information technology programmes in Kazakhstan.', 'Kazakhstan', ARRAY['bachelor','master'], null, 'partial', 'Partial to full tuition', null, 'https://astanait.edu.kz/en', 3.30, 6.0, 78, null, false, false, null, null, null, null),

-- ============================ Hungary, Czechia, Poland ============================
('Central European University Scholarship', 'Central European University', 'Merit and need based scholarships for graduate students at CEU in Vienna and Budapest.', 'Hungary', ARRAY['master','phd'], null, 'full', 'Tuition and stipend', null, 'https://www.ceu.edu/financialaid', 3.50, 6.5, 90, null, true, true, null, null, null, null),
('Corvinus University Scholarship', 'Corvinus University of Budapest', 'Merit scholarships for international students in business and social sciences.', 'Hungary', ARRAY['bachelor','master'], null, 'partial', 'Partial tuition', null, 'https://www.uni-corvinus.hu/main/admissions/scholarships', 3.30, 6.0, 80, null, false, false, null, null, null, null),
('Czech Government Scholarship', 'Czech Ministry of Education', 'Scholarships for students from developing countries to study at public universities in Czechia.', 'Czechia', ARRAY['bachelor','master','phd'], null, 'full', 'Tuition and living allowance', null, 'https://www.msmt.cz/eu-and-international-affairs/scholarships', 3.20, 6.0, 80, null, true, true, null, null, null, null),
('Charles University Scholarship', 'Charles University', 'Scholarships and support for international students at Charles University in Prague.', 'Czechia', ARRAY['master','phd'], null, 'partial', 'Varies', null, 'https://cuni.cz/UKEN-116.html', 3.30, 6.0, 80, null, false, false, null, null, null, null),
('Lodz University of Technology Scholarship', 'Lodz University of Technology', 'Scholarships for international students in engineering programmes in Poland.', 'Poland', ARRAY['bachelor','master'], null, 'partial', 'Tuition reduction', null, 'https://www.p.lodz.pl/en', 3.20, 6.0, 79, null, false, false, null, null, null, null),
('University of Warsaw Scholarship', 'University of Warsaw', 'Scholarships and support for international students at the University of Warsaw.', 'Poland', ARRAY['master'], null, 'partial', 'Varies', null, 'https://en.uw.edu.pl', 3.30, 6.0, 80, null, false, false, null, null, null, null),

-- ============================ Additional destinations (Asia, Middle East, Americas) ============================
('Hong Kong PhD Fellowship Scheme', 'Hong Kong Research Grants Council', 'Fully funded PhD fellowship for outstanding international students at Hong Kong universities.', 'Hong Kong', ARRAY['phd'], null, 'full', 'HKD 331,200 stipend per year plus travel', null, 'https://cerg1.ugc.edu.hk/hkpfs', 3.60, 6.5, 90, null, true, true, null, null, null, null),
('HKU Foundation Entrance Scholarship', 'University of Hong Kong', 'Merit scholarships for outstanding international undergraduates at HKU.', 'Hong Kong', ARRAY['bachelor'], null, 'partial', 'Tuition and living support', null, 'https://www.hku.hk/admission', 3.60, 6.5, 90, 1400, true, true, null, null, null, null),
('HKUST Postgraduate Scholarship', 'Hong Kong University of Science and Technology', 'Scholarships and studentships for international postgraduate research students.', 'Hong Kong', ARRAY['master','phd'], null, 'full', 'Tuition and stipend', null, 'https://pg.ust.hk', 3.50, 6.5, 90, null, false, true, null, null, null, null),
('CUHK Vice-Chancellor Scholarship', 'Chinese University of Hong Kong', 'Full scholarship for exceptional international undergraduate students at CUHK.', 'Hong Kong', ARRAY['bachelor'], null, 'full', 'Tuition, hostel and travel', null, 'https://www.cuhk.edu.hk/english/admission', 3.70, 6.5, 90, 1400, true, true, null, null, null, null),
('Taiwan Scholarship', 'Taiwan Ministry of Education', 'Scholarship for international students to pursue degrees at universities in Taiwan.', 'Taiwan', ARRAY['bachelor','master','phd'], null, 'full', 'Tuition and monthly stipend', null, 'https://www.studyintaiwan.org', 3.30, 6.0, 80, null, true, true, null, null, null, null),
('National Taiwan University Scholarship', 'National Taiwan University', 'Scholarships for international students at NTU.', 'Taiwan', ARRAY['master','phd'], null, 'partial', 'Tuition and stipend', null, 'https://www.ntu.edu.tw/english', 3.40, 6.5, 88, null, false, true, null, null, null, null),
('NYCU International Scholarship', 'National Yang Ming Chiao Tung University', 'Scholarships for international students in technology and science programmes in Taiwan.', 'Taiwan', ARRAY['master','phd'], null, 'partial', 'Tuition and stipend', null, 'https://www.nycu.edu.tw/nycu/en', 3.30, 6.0, 80, null, false, false, null, null, null, null),
('Malaysia International Scholarship', 'Malaysian Ministry of Higher Education', 'Scholarship for international students to pursue postgraduate study in Malaysia.', 'Malaysia', ARRAY['master','phd'], null, 'full', 'Tuition and monthly allowance', null, 'https://biasiswa.mohe.gov.my/INTER', 3.50, 6.5, 90, null, true, true, null, null, null, null),
('Universiti Malaya Scholarship', 'Universiti Malaya', 'Merit scholarships for international postgraduate students in Malaysia.', 'Malaysia', ARRAY['master','phd'], null, 'partial', 'Tuition support', null, 'https://www.um.edu.my', 3.30, 6.0, 80, null, false, false, null, null, null, null),
('KAUST Fellowship', 'King Abdullah University of Science and Technology', 'Fully funded fellowship for graduate students in science and engineering.', 'Saudi Arabia', ARRAY['master','phd'], null, 'full', 'Tuition, stipend, housing and insurance', null, 'https://www.kaust.edu.sa/en/study/how-to-apply', 3.40, 6.5, 79, null, true, true, null, null, null, null),
('KFUPM Graduate Scholarship', 'King Fahd University of Petroleum and Minerals', 'Scholarships for international graduate students in engineering and science.', 'Saudi Arabia', ARRAY['master','phd'], null, 'full', 'Tuition, stipend and housing', null, 'https://www.kfupm.edu.sa/en', 3.30, 6.0, 79, null, false, true, null, null, null, null),
('Hamad Bin Khalifa University Scholarship', 'Hamad Bin Khalifa University', 'Scholarships for international graduate students at HBKU in Qatar.', 'Qatar', ARRAY['master','phd'], null, 'full', 'Tuition, stipend and housing', null, 'https://www.hbku.edu.qa', 3.40, 6.5, 79, null, true, true, null, null, null, null),
('Khalifa University Scholarship', 'Khalifa University', 'Scholarships for international graduate students in science and engineering in the UAE.', 'United Arab Emirates', ARRAY['master','phd'], null, 'full', 'Tuition, stipend and housing', null, 'https://www.ku.ac.ae', 3.40, 6.5, 91, null, false, true, null, null, null, null),
('ICCR India Scholarship', 'Indian Council for Cultural Relations', 'Scholarship for international students to study in India across levels.', 'India', ARRAY['bachelor','master','phd'], null, 'full', 'Tuition and living allowance', null, 'https://www.iccr.gov.in', 3.00, 5.5, 79, null, true, true, null, null, null, null),
('IIT Research Fellowship', 'Indian Institutes of Technology', 'Research fellowships for international postgraduate students at the IITs.', 'India', ARRAY['master','phd'], null, 'partial', 'Stipend and tuition support', null, 'https://www.iitsystem.ac.in', 3.30, 6.0, 79, null, false, true, null, null, null, null),
('OAS Academic Scholarship', 'Organization of American States', 'Scholarships for citizens of member states for graduate study in the Americas.', 'Multiple countries', ARRAY['master','phd'], null, 'partial', 'Tuition support', null, 'https://www.oas.org/en/scholarships', 3.20, 6.0, 80, null, true, true, null, null, null, null),
('Brazil PEC-PG Scholarship', 'Brazilian Government', 'Scholarship for students from developing countries for postgraduate study in Brazil.', 'Brazil', ARRAY['master','phd'], null, 'full', 'Monthly stipend', null, 'https://www.gov.br/capes', 3.20, null, null, null, true, true, null, null, null, null),
('Estonian Government Dora Plus Scholarship', 'Estonian Government', 'Scholarships for international students studying at Estonian universities.', 'Estonia', ARRAY['master','phd'], null, 'partial', 'Monthly allowance', null, 'https://haridus.archimedes.ee/en', 3.30, 6.0, 80, null, false, false, null, null, null, null),
('University of Lisbon Scholarship', 'University of Lisbon', 'Scholarships and support for international students at the University of Lisbon.', 'Portugal', ARRAY['master'], null, 'partial', 'Varies', null, 'https://www.ulisboa.pt/en', 3.30, 6.0, 80, null, false, false, null, null, null, null),
('Freeman Asian Scholarship', 'Wesleyan University', 'Full tuition scholarship for outstanding students from Asian countries at Wesleyan.', 'United States', ARRAY['bachelor'], null, 'full', 'Full tuition for four years', null, 'https://www.wesleyan.edu/admission/afees/scholarships.html', 3.80, 7.0, 100, 1450, true, true, null, null, null, null),
('Columbia University Financial Aid', 'Columbia University', 'Need based financial aid available to admitted undergraduates including internationals. Admission is highly competitive.', 'United States', ARRAY['bachelor'], null, 'full', 'Meets full demonstrated need', null, 'https://cc-seas.financialaid.columbia.edu', 3.90, 7.0, 100, 1500, true, true, null, null, null, null),
('Duke University Financial Aid', 'Duke University', 'Need based aid for undergraduates, available to international students who apply for aid.', 'United States', ARRAY['bachelor'], null, 'partial', 'Need based aid', null, 'https://financialaid.duke.edu', 3.90, 7.0, 100, 1500, true, true, null, null, null, null),
('University of Chicago Financial Aid', 'University of Chicago', 'Need based aid for undergraduates including international students.', 'United States', ARRAY['bachelor'], null, 'full', 'Meets full demonstrated need', null, 'https://collegeadmissions.uchicago.edu/afford', 3.90, 7.0, 100, 1510, true, true, null, null, null, null),
('Cornell University Financial Aid', 'Cornell University', 'Need based financial aid for undergraduates including international applicants.', 'United States', ARRAY['bachelor'], null, 'partial', 'Need based aid', null, 'https://finaid.cornell.edu', 3.80, 7.0, 100, 1470, true, true, null, null, null, null),
('Cambridge Trust Scholarship', 'University of Cambridge', 'Scholarships for international students across levels at the University of Cambridge.', 'United Kingdom', ARRAY['master','phd'], null, 'partial', 'Partial to full funding', null, 'https://www.cambridgetrust.org', 3.70, 7.0, 100, null, true, true, null, null, null, null),
('Oxford Reach Scholarship', 'University of Oxford', 'Scholarships supporting talented students from around the world at Oxford.', 'United Kingdom', ARRAY['master'], null, 'full', 'Tuition and living costs', null, 'https://www.ox.ac.uk/admissions/graduate/fees-and-funding', 3.70, 7.0, 100, null, true, true, null, null, null, null),
('Imperial College Presidential Scholarship', 'Imperial College London', 'Scholarships for outstanding students in science, engineering, medicine and business.', 'United Kingdom', ARRAY['master','phd'], null, 'partial', 'Tuition and or stipend', null, 'https://www.imperial.ac.uk/study/fees-and-funding', 3.60, 6.5, 92, null, false, true, null, null, null, null),
('LSE Graduate Support Scheme', 'London School of Economics', 'Need based financial support for graduate students at LSE.', 'United Kingdom', ARRAY['master'], null, 'partial', 'Up to GBP 15,000', null, 'https://www.lse.ac.uk/study-at-lse/Graduate/fees-and-funding', 3.50, 7.0, 100, null, false, false, null, null, null, null),
('SEED-Net Scholarship', 'ASEAN University Network and JICA', 'Scholarship for engineering graduate study among ASEAN member universities.', 'Thailand', ARRAY['master','phd'], null, 'full', 'Tuition and stipend', null, 'https://seed-net.org', 3.30, 6.0, 79, null, true, true, null, null, null, null),
('Israeli Government Scholarship', 'Israeli Ministry of Foreign Affairs', 'Scholarships for international students for study and research at Israeli universities.', 'Israel', ARRAY['master','phd'], null, 'partial', 'Monthly stipend and tuition', null, 'https://embassies.gov.il', 3.30, 6.5, 89, null, true, true, null, null, null, null),
('AMEXCID Mexican Government Scholarship', 'Mexican Agency for International Development Cooperation', 'Scholarships for international students for study and research in Mexico.', 'Mexico', ARRAY['master','phd'], null, 'full', 'Tuition and monthly stipend', null, 'https://www.gob.mx/amexcid', 3.20, null, null, null, true, true, null, null, null, null);
